---
- hosts: localhost
  connection: local
  environment: "{{ ansible_env | default({}) }}"

  tasks:
    - name: print the test environment variable from GH
      ansible.builtin.shell: echo "The secret is $MY_PULL_VAR"
      register: command_output

    - name: show output
      ansible.builtin.debug:
        var: command_output.stdout

